### ISSUE TITLE
I broke continuous integration

### ISSUE THREAD

**Issue by poke1024** [scikit-geometry/scikit-geometry#31]
This got broken with https://github.com/scikit-geometry/scikit-geometry/pull/26

I shouldn't use `std::optional`, since VS doesn't know it. Maybe switching to `boost::optional` is better?

```
   polygon.cpp
    C:\condaskgeom\Library\include\CGAL/GMP/Gmpzf_type.h(461): warning C4244: 'initializing': conversion from 'mp_bitcnt_t' to 'unsigned long', possible loss of data
    C:\condaskgeom\Library\include\CGAL/GMP/Gmpfr_type.h(1020): warning C4244: 'initializing': conversion from 'mp_bitcnt_t' to 'long', possible loss of data
    C:\condaskgeom\Library\include\CGAL/GMP/Gmpfr_type.h(1145): warning C4244: 'argument': conversion from 'mpir_ui' to 'unsigned long', possible loss of data
    C:\condaskgeom\Library\include\CGAL/GMP/Gmpfr_type.h(1147): warning C4244: 'argument': conversion from 'mpir_ui' to 'unsigned long', possible loss of data
    src/polygon.cpp(80): error C2039: 'optional': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\valarray(15): note: see declaration of 'std'
    src/polygon.cpp(80): error C2065: 'optional': undeclared identifier
    src/polygon.cpp(80): error C2275: 'CGAL::Random': illegal use of this type as an expression
    src/polygon.cpp(80): note: see declaration of 'CGAL::Random'
    src/polygon.cpp(80): error C2065: 'custom_random': undeclared identifier
    src/polygon.cpp(82): error C2065: 'custom_random': undeclared identifier
    src/polygon.cpp(84): error C2065: 'custom_random': undeclared identifier
    src/polygon.cpp(84): error C2530: 'random': references must be initialized
    src/polygon.cpp(88): error C3536: 'random': cannot be used before it is initialized
    src/polygon.cpp(88): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'CGAL::Random_points_in_square_2<Point_2,CGAL::Creator_uniform_2<CGAL::Lazy_exact_nt<CGAL::Gmpq>,P>>'
            with
            [
                P=Point_2
            ]
    src/polygon.cpp(88): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    src/polygon.cpp(88): error C2672: 'CGAL::random_polygon_2': no matching overloaded function found
    src/polygon.cpp(88): error C2780: 'OutputIterator CGAL::random_polygon_2(std::size_t,OutputIterator,const PointGenerator &)': expects 3 arguments - 2 provided
    C:\condaskgeom\Library\include\CGAL/random_polygon_2.h(74): note: see declaration of 'CGAL::random_polygon_2'
    src/polygon.cpp(88): error C2780: 'OutputIterator CGAL::random_polygon_2(std::size_t,OutputIterator,const PointGenerator &,const Traits &)': expects 4 arguments - 2 provided
    C:\condaskgeom\Library\include\CGAL/random_polygon_2.h(47): note: see declaration of 'CGAL::random_polygon_2'
    src/polygon.cpp(91): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'CGAL::Random_points_in_disc_2<Point_2,CGAL::Creator_uniform_2<CGAL::Lazy_exact_nt<CGAL::Gmpq>,P>>'
            with
            [
                P=Point_2
            ]
    src/polygon.cpp(91): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    src/polygon.cpp(91): error C2672: 'CGAL::random_polygon_2': no matching overloaded function found
    src/polygon.cpp(91): error C2780: 'OutputIterator CGAL::random_polygon_2(std::size_t,OutputIterator,const PointGenerator &)': expects 3 arguments - 2 provided
    C:\condaskgeom\Library\include\CGAL/random_polygon_2.h(74): note: see declaration of 'CGAL::random_polygon_2'
    src/polygon.cpp(91): error C2780: 'OutputIterator CGAL::random_polygon_2(std::size_t,OutputIterator,const PointGenerator &,const Traits &)': expects 4 arguments - 2 provided
    C:\condaskgeom\Library\include\CGAL/random_polygon_2.h(47): note: see declaration of 'CGAL::random_polygon_2'
    src/polygon.cpp(94): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'CGAL::Random_points_on_circle_2<Point_2,CGAL::Creator_uniform_2<CGAL::Lazy_exact_nt<CGAL::Gmpq>,P>>'
            with
            [
                P=Point_2
            ]
    src/polygon.cpp(94): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    src/polygon.cpp(94): error C2672: 'CGAL::random_polygon_2': no matching overloaded function found
    src/polygon.cpp(94): error C2780: 'OutputIterator CGAL::random_polygon_2(std::size_t,OutputIterator,const PointGenerator &)': expects 3 arguments - 2 provided
    C:\condaskgeom\Library\include\CGAL/random_polygon_2.h(74): note: see declaration of 'CGAL::random_polygon_2'
    src/polygon.cpp(94): error C2780: 'OutputIterator CGAL::random_polygon_2(std::size_t,OutputIterator,const PointGenerator &,const Traits &)': expects 4 arguments - 2 provided
    C:\condaskgeom\Library\include\CGAL/random_polygon_2.h(47): note: see declaration of 'CGAL::random_polygon_2'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ERROR: Can't roll back skgeom; was not uninstalled
```

**Comment by wolfv** [comment]
ah yes, how annoying. yep, i think boost::optional would be appropriate (since we're relying on boost implicitly anyways...)

It was kind-of my fault as we renamed the repo and didn't turn CI on right away :)
