### PR TITLE
Ensure pybind11 is correct version

### PR DESCRIPTION
**Pull request by geographika**
With #84 the older pybind11 version 2.7 no longer builds. This ensures a minimum of 2.8 is required. 

Otherwise errors such as the following are thrown:

```
        src/arrangement.cpp: In function ‘pybind11::iterator skgeom::make_handle_iterator(Iterator, Sentinel, Extra&& ...)’:
        src/arrangement.cpp:104:21: error: ‘iterator_access’ is not a member of ‘pybind11::detail’
          104 |             detail::iterator_access<Iterator>, Policy, Iterator, Sentinel, ValueType
```

### CODE REVIEW

**Comment by skrat** [comment]
I had different error related to pybind11 version, and had to bump the upper limit to 2.12, to make this work with Python 3.11
